/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedChatsRouteImport } from './routes/_authenticated/chats'
import { Route as AuthenticatedEpisodesIndexRouteImport } from './routes/_authenticated/episodes/index'
import { Route as AuthenticatedCompaniesIndexRouteImport } from './routes/_authenticated/companies/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthenticatedEpisodesEpisodeIdRouteImport } from './routes/_authenticated/episodes/$episodeId'
import { Route as AuthenticatedChatsChatIdRouteImport } from './routes/_authenticated/chats/$chatId'
import { Route as AuthenticatedCompaniesCompanyIdProjectsRouteImport } from './routes/_authenticated/companies/$companyId.projects'
import { Route as AuthenticatedProjectsProjectIdLogsIndexRouteImport } from './routes/_authenticated/projects/$projectId/logs/index'
import { Route as AuthenticatedProjectsProjectIdLogsLogIdRouteImport } from './routes/_authenticated/projects/$projectId/logs/$logId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedChatsRoute = AuthenticatedChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEpisodesIndexRoute =
  AuthenticatedEpisodesIndexRouteImport.update({
    id: '/episodes/',
    path: '/episodes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCompaniesIndexRoute =
  AuthenticatedCompaniesIndexRouteImport.update({
    id: '/companies/',
    path: '/companies/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedChatsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEpisodesEpisodeIdRoute =
  AuthenticatedEpisodesEpisodeIdRouteImport.update({
    id: '/episodes/$episodeId',
    path: '/episodes/$episodeId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedChatsChatIdRoute =
  AuthenticatedChatsChatIdRouteImport.update({
    id: '/$chatId',
    path: '/$chatId',
    getParentRoute: () => AuthenticatedChatsRoute,
  } as any)
const AuthenticatedCompaniesCompanyIdProjectsRoute =
  AuthenticatedCompaniesCompanyIdProjectsRouteImport.update({
    id: '/companies/$companyId/projects',
    path: '/companies/$companyId/projects',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectIdLogsIndexRoute =
  AuthenticatedProjectsProjectIdLogsIndexRouteImport.update({
    id: '/projects/$projectId/logs/',
    path: '/projects/$projectId/logs/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectIdLogsLogIdRoute =
  AuthenticatedProjectsProjectIdLogsLogIdRouteImport.update({
    id: '/projects/$projectId/logs/$logId',
    path: '/projects/$projectId/logs/$logId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/chats': typeof AuthenticatedChatsRouteWithChildren
  '/chats/$chatId': typeof AuthenticatedChatsChatIdRoute
  '/episodes/$episodeId': typeof AuthenticatedEpisodesEpisodeIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/chats/': typeof AuthenticatedChatsIndexRoute
  '/companies/': typeof AuthenticatedCompaniesIndexRoute
  '/episodes/': typeof AuthenticatedEpisodesIndexRoute
  '/companies/$companyId/projects': typeof AuthenticatedCompaniesCompanyIdProjectsRoute
  '/projects/$projectId/logs/$logId': typeof AuthenticatedProjectsProjectIdLogsLogIdRoute
  '/projects/$projectId/logs/': typeof AuthenticatedProjectsProjectIdLogsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/chats/$chatId': typeof AuthenticatedChatsChatIdRoute
  '/episodes/$episodeId': typeof AuthenticatedEpisodesEpisodeIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/companies': typeof AuthenticatedCompaniesIndexRoute
  '/episodes': typeof AuthenticatedEpisodesIndexRoute
  '/companies/$companyId/projects': typeof AuthenticatedCompaniesCompanyIdProjectsRoute
  '/projects/$projectId/logs/$logId': typeof AuthenticatedProjectsProjectIdLogsLogIdRoute
  '/projects/$projectId/logs': typeof AuthenticatedProjectsProjectIdLogsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/_authenticated/chats': typeof AuthenticatedChatsRouteWithChildren
  '/_authenticated/chats/$chatId': typeof AuthenticatedChatsChatIdRoute
  '/_authenticated/episodes/$episodeId': typeof AuthenticatedEpisodesEpisodeIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/companies/': typeof AuthenticatedCompaniesIndexRoute
  '/_authenticated/episodes/': typeof AuthenticatedEpisodesIndexRoute
  '/_authenticated/companies/$companyId/projects': typeof AuthenticatedCompaniesCompanyIdProjectsRoute
  '/_authenticated/projects/$projectId/logs/$logId': typeof AuthenticatedProjectsProjectIdLogsLogIdRoute
  '/_authenticated/projects/$projectId/logs/': typeof AuthenticatedProjectsProjectIdLogsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/signup'
    | '/chats'
    | '/chats/$chatId'
    | '/episodes/$episodeId'
    | '/api/auth/$'
    | '/chats/'
    | '/companies/'
    | '/episodes/'
    | '/companies/$companyId/projects'
    | '/projects/$projectId/logs/$logId'
    | '/projects/$projectId/logs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/signup'
    | '/chats/$chatId'
    | '/episodes/$episodeId'
    | '/api/auth/$'
    | '/chats'
    | '/companies'
    | '/episodes'
    | '/companies/$companyId/projects'
    | '/projects/$projectId/logs/$logId'
    | '/projects/$projectId/logs'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/signin'
    | '/signup'
    | '/_authenticated/chats'
    | '/_authenticated/chats/$chatId'
    | '/_authenticated/episodes/$episodeId'
    | '/api/auth/$'
    | '/_authenticated/chats/'
    | '/_authenticated/companies/'
    | '/_authenticated/episodes/'
    | '/_authenticated/companies/$companyId/projects'
    | '/_authenticated/projects/$projectId/logs/$logId'
    | '/_authenticated/projects/$projectId/logs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/chats': {
      id: '/_authenticated/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/episodes/': {
      id: '/_authenticated/episodes/'
      path: '/episodes'
      fullPath: '/episodes/'
      preLoaderRoute: typeof AuthenticatedEpisodesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/companies/': {
      id: '/_authenticated/companies/'
      path: '/companies'
      fullPath: '/companies/'
      preLoaderRoute: typeof AuthenticatedCompaniesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/'
      fullPath: '/chats/'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedChatsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/episodes/$episodeId': {
      id: '/_authenticated/episodes/$episodeId'
      path: '/episodes/$episodeId'
      fullPath: '/episodes/$episodeId'
      preLoaderRoute: typeof AuthenticatedEpisodesEpisodeIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chats/$chatId': {
      id: '/_authenticated/chats/$chatId'
      path: '/$chatId'
      fullPath: '/chats/$chatId'
      preLoaderRoute: typeof AuthenticatedChatsChatIdRouteImport
      parentRoute: typeof AuthenticatedChatsRoute
    }
    '/_authenticated/companies/$companyId/projects': {
      id: '/_authenticated/companies/$companyId/projects'
      path: '/companies/$companyId/projects'
      fullPath: '/companies/$companyId/projects'
      preLoaderRoute: typeof AuthenticatedCompaniesCompanyIdProjectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId/logs/': {
      id: '/_authenticated/projects/$projectId/logs/'
      path: '/projects/$projectId/logs'
      fullPath: '/projects/$projectId/logs/'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdLogsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId/logs/$logId': {
      id: '/_authenticated/projects/$projectId/logs/$logId'
      path: '/projects/$projectId/logs/$logId'
      fullPath: '/projects/$projectId/logs/$logId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdLogsLogIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedChatsRouteChildren {
  AuthenticatedChatsChatIdRoute: typeof AuthenticatedChatsChatIdRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
}

const AuthenticatedChatsRouteChildren: AuthenticatedChatsRouteChildren = {
  AuthenticatedChatsChatIdRoute: AuthenticatedChatsChatIdRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
}

const AuthenticatedChatsRouteWithChildren =
  AuthenticatedChatsRoute._addFileChildren(AuthenticatedChatsRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedChatsRoute: typeof AuthenticatedChatsRouteWithChildren
  AuthenticatedEpisodesEpisodeIdRoute: typeof AuthenticatedEpisodesEpisodeIdRoute
  AuthenticatedCompaniesIndexRoute: typeof AuthenticatedCompaniesIndexRoute
  AuthenticatedEpisodesIndexRoute: typeof AuthenticatedEpisodesIndexRoute
  AuthenticatedCompaniesCompanyIdProjectsRoute: typeof AuthenticatedCompaniesCompanyIdProjectsRoute
  AuthenticatedProjectsProjectIdLogsLogIdRoute: typeof AuthenticatedProjectsProjectIdLogsLogIdRoute
  AuthenticatedProjectsProjectIdLogsIndexRoute: typeof AuthenticatedProjectsProjectIdLogsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedChatsRoute: AuthenticatedChatsRouteWithChildren,
  AuthenticatedEpisodesEpisodeIdRoute: AuthenticatedEpisodesEpisodeIdRoute,
  AuthenticatedCompaniesIndexRoute: AuthenticatedCompaniesIndexRoute,
  AuthenticatedEpisodesIndexRoute: AuthenticatedEpisodesIndexRoute,
  AuthenticatedCompaniesCompanyIdProjectsRoute:
    AuthenticatedCompaniesCompanyIdProjectsRoute,
  AuthenticatedProjectsProjectIdLogsLogIdRoute:
    AuthenticatedProjectsProjectIdLogsLogIdRoute,
  AuthenticatedProjectsProjectIdLogsIndexRoute:
    AuthenticatedProjectsProjectIdLogsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
