/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedCompaniesIndexRouteImport } from './routes/_authenticated/companies/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthenticatedCompaniesCompanyIdProjectsRouteImport } from './routes/_authenticated/companies/$companyId.projects'
import { Route as AuthenticatedProjectsProjectIdLogsIndexRouteImport } from './routes/_authenticated/projects/$projectId/logs/index'
import { Route as AuthenticatedProjectsProjectIdLogsLogIdRouteImport } from './routes/_authenticated/projects/$projectId/logs/$logId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCompaniesIndexRoute =
  AuthenticatedCompaniesIndexRouteImport.update({
    id: '/companies/',
    path: '/companies/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCompaniesCompanyIdProjectsRoute =
  AuthenticatedCompaniesCompanyIdProjectsRouteImport.update({
    id: '/companies/$companyId/projects',
    path: '/companies/$companyId/projects',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectIdLogsIndexRoute =
  AuthenticatedProjectsProjectIdLogsIndexRouteImport.update({
    id: '/projects/$projectId/logs/',
    path: '/projects/$projectId/logs/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectIdLogsLogIdRoute =
  AuthenticatedProjectsProjectIdLogsLogIdRouteImport.update({
    id: '/projects/$projectId/logs/$logId',
    path: '/projects/$projectId/logs/$logId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/companies/': typeof AuthenticatedCompaniesIndexRoute
  '/companies/$companyId/projects': typeof AuthenticatedCompaniesCompanyIdProjectsRoute
  '/projects/$projectId/logs/$logId': typeof AuthenticatedProjectsProjectIdLogsLogIdRoute
  '/projects/$projectId/logs/': typeof AuthenticatedProjectsProjectIdLogsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/companies': typeof AuthenticatedCompaniesIndexRoute
  '/companies/$companyId/projects': typeof AuthenticatedCompaniesCompanyIdProjectsRoute
  '/projects/$projectId/logs/$logId': typeof AuthenticatedProjectsProjectIdLogsLogIdRoute
  '/projects/$projectId/logs': typeof AuthenticatedProjectsProjectIdLogsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authenticated/companies/': typeof AuthenticatedCompaniesIndexRoute
  '/_authenticated/companies/$companyId/projects': typeof AuthenticatedCompaniesCompanyIdProjectsRoute
  '/_authenticated/projects/$projectId/logs/$logId': typeof AuthenticatedProjectsProjectIdLogsLogIdRoute
  '/_authenticated/projects/$projectId/logs/': typeof AuthenticatedProjectsProjectIdLogsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/signup'
    | '/api/auth/$'
    | '/companies/'
    | '/companies/$companyId/projects'
    | '/projects/$projectId/logs/$logId'
    | '/projects/$projectId/logs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/signup'
    | '/api/auth/$'
    | '/companies'
    | '/companies/$companyId/projects'
    | '/projects/$projectId/logs/$logId'
    | '/projects/$projectId/logs'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/signin'
    | '/signup'
    | '/api/auth/$'
    | '/_authenticated/companies/'
    | '/_authenticated/companies/$companyId/projects'
    | '/_authenticated/projects/$projectId/logs/$logId'
    | '/_authenticated/projects/$projectId/logs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/companies/': {
      id: '/_authenticated/companies/'
      path: '/companies'
      fullPath: '/companies/'
      preLoaderRoute: typeof AuthenticatedCompaniesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/companies/$companyId/projects': {
      id: '/_authenticated/companies/$companyId/projects'
      path: '/companies/$companyId/projects'
      fullPath: '/companies/$companyId/projects'
      preLoaderRoute: typeof AuthenticatedCompaniesCompanyIdProjectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId/logs/': {
      id: '/_authenticated/projects/$projectId/logs/'
      path: '/projects/$projectId/logs'
      fullPath: '/projects/$projectId/logs/'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdLogsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId/logs/$logId': {
      id: '/_authenticated/projects/$projectId/logs/$logId'
      path: '/projects/$projectId/logs/$logId'
      fullPath: '/projects/$projectId/logs/$logId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdLogsLogIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCompaniesIndexRoute: typeof AuthenticatedCompaniesIndexRoute
  AuthenticatedCompaniesCompanyIdProjectsRoute: typeof AuthenticatedCompaniesCompanyIdProjectsRoute
  AuthenticatedProjectsProjectIdLogsLogIdRoute: typeof AuthenticatedProjectsProjectIdLogsLogIdRoute
  AuthenticatedProjectsProjectIdLogsIndexRoute: typeof AuthenticatedProjectsProjectIdLogsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCompaniesIndexRoute: AuthenticatedCompaniesIndexRoute,
  AuthenticatedCompaniesCompanyIdProjectsRoute:
    AuthenticatedCompaniesCompanyIdProjectsRoute,
  AuthenticatedProjectsProjectIdLogsLogIdRoute:
    AuthenticatedProjectsProjectIdLogsLogIdRoute,
  AuthenticatedProjectsProjectIdLogsIndexRoute:
    AuthenticatedProjectsProjectIdLogsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
